"use client";

import { useState, useEffect } from "react";
import Link from "next/link";

const CODE_LINES = [
  { text: 'import { McpServer } from "@modelcontextprotocol/sdk";', color: "#c084fc" },
  { text: "", color: "" },
  { text: "const server = new McpServer({", color: "#94a3b8" },
  { text: '  name: "inventory-api",', color: "#22c55e" },
  { text: '  version: "1.0.0",', color: "#22c55e" },
  { text: "});", color: "#94a3b8" },
  { text: "", color: "" },
  { text: "server.tool(", color: "#f59e0b" },
  { text: '  "search_vehicles",', color: "#22c55e" },
  { text: '  "Search inventory by make, model, year",', color: "#22c55e" },
  { text: "  { make: z.string(), year: z.number() },", color: "#94a3b8" },
  { text: "  async ({ make, year }) => {", color: "#c084fc" },
  { text: "    const results = await db.query(make, year);", color: "#94a3b8" },
  { text: "    return { content: [{ type: 'text', text: results }] };", color: "#94a3b8" },
  { text: "  }", color: "#c084fc" },
  { text: ");", color: "#f59e0b" },
];

export default function Hero() {
  const [visibleLines, setVisibleLines] = useState(0);
  const [mounted, setMounted] = useState(false);

  useEffect(() => { setMounted(true); }, []);

  useEffect(() => {
    const timer = setInterval(() => {
      setVisibleLines((prev) => (prev < CODE_LINES.length ? prev + 1 : prev));
    }, 120);
    return () => clearInterval(timer);
  }, []);

  return (
    <section className="px-6 pt-20 pb-16">
      <div className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
        <div className={`transition-all duration-1000 ${mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}>
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-forge-500/8 border border-forge-500/20 rounded-full mb-6">
            <span className="w-2 h-2 rounded-full bg-forge-500 animate-pulse" />
            <span className="text-[10px] font-mono text-forge-400 font-semibold tracking-wider uppercase">
              MCP Spec 2025-11-25
            </span>
          </div>
          <h1 className="text-4xl lg:text-5xl font-bold leading-tight mb-6 tracking-tight">
            Build MCP Servers<br />
            <span className="text-forge-400">Visually.</span>
          </h1>
          <p className="text-lg text-slate-400 leading-relaxed mb-8 max-w-lg">
            Stop writing boilerplate. Design tools, resources, and prompts through a visual interface — get production-ready TypeScript code that follows the official SDK patterns.
          </p>
          <div className="flex gap-4">
            <Link href="/builder" className="px-6 py-3 bg-forge-500 hover:bg-forge-600 text-white font-mono font-semibold text-sm rounded-lg transition-all glow-green">
              Start Building →
            </Link>
            <a href="https://github.com/mpalmer79/mcp-forge" className="px-6 py-3 bg-white/[0.03] border border-white/[0.08] hover:border-white/[0.15] text-slate-300 font-mono text-sm rounded-lg transition-all" target="_blank" rel="noopener noreferrer">
              View Source
            </a>
          </div>
        </div>
        <div className={`transition-all duration-1000 delay-300 ${mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}>
          <div className="code-block relative overflow-hidden">
            <div className="flex gap-2 mb-4 pb-3 border-b border-white/5">
              <div className="w-3 h-3 rounded-full bg-red-500/60" />
              <div className="w-3 h-3 rounded-full bg-yellow-500/60" />
              <div className="w-3 h-3 rounded-full bg-green-500/60" />
              <span className="ml-3 text-[10px] text-slate-600 font-mono">index.ts — generated by MCP Forge</span>
            </div>
            {CODE_LINES.slice(0, visibleLines).map((line, i) => (
              <div key={i} className="font-mono text-[11px] leading-relaxed animate-fade-in" style={{ color: line.color || "#475569" }}>
                {line.text || "\u00A0"}
              </div>
            ))}
            {visibleLines < CODE_LINES.length && (
              <span className="inline-block w-2 h-4 bg-forge-500 ml-1" style={{ animation: "blink 0.8s infinite" }} />
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
