"use client";

import { useState, useEffect } from "react";
import Link from "next/link";

// animated terminal code snippet
const CODE_LINES = [
  { text: 'import { McpServer } from "@modelcontextprotocol/sdk";', color: "#c084fc" },
  { text: "", color: "" },
  { text: "const server = new McpServer({", color: "#94a3b8" },
  { text: '  name: "inventory-api",', color: "#22c55e" },
  { text: '  version: "1.0.0",', color: "#22c55e" },
  { text: "});", color: "#94a3b8" },
  { text: "", color: "" },
  { text: "server.tool(", color: "#f59e0b" },
  { text: '  "search_vehicles",', color: "#22c55e" },
  { text: '  "Search inventory by make, model, year",', color: "#22c55e" },
  { text: "  { make: z.string(), year: z.number() },", color: "#94a3b8" },
  { text: "  async ({ make, year }) => {", color: "#c084fc" },
  { text: "    const results = await db.query(make, year);", color: "#94a3b8" },
  { text: "    return { content: [{ type: 'text', text: results }] };", color: "#94a3b8" },
  { text: "  }", color: "#c084fc" },
  { text: ");", color: "#f59e0b" },
];

function AnimatedCode() {
  const [visibleLines, setVisibleLines] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setVisibleLines((prev) => (prev < CODE_LINES.length ? prev + 1 : prev));
    }, 120);
    return () => clearInterval(timer);
  }, []);

  return (
    <div className="code-block relative overflow-hidden">
      {/* terminal header dots */}
      <div className="flex gap-2 mb-4 pb-3 border-b border-white/5">
        <div className="w-3 h-3 rounded-full bg-red-500/60" />
        <div className="w-3 h-3 rounded-full bg-yellow-500/60" />
        <div className="w-3 h-3 rounded-full bg-green-500/60" />
        <span className="ml-3 text-[10px] text-slate-600 font-mono">
          index.ts — generated by MCP Forge
        </span>
      </div>
      {CODE_LINES.slice(0, visibleLines).map((line, i) => (
        <div
          key={i}
          className="font-mono text-[11px] leading-relaxed animate-fade-in"
          style={{ color: line.color || "#475569" }}
        >
          {line.text || "\u00A0"}
        </div>
      ))}
      {visibleLines < CODE_LINES.length && (
        <span className="inline-block w-2 h-4 bg-forge-500 ml-1" style={{ animation: "blink 0.8s infinite" }} />
      )}
    </div>
  );
}

const FEATURES = [
  {
    title: "Visual Builder",
    desc: "Design MCP servers by clicking, not coding. Add tools with typed parameters, resources with URI patterns, and prompt templates.",
    color: "#22c55e",
    photo: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop&q=80",
  },
  {
    title: "Server Registry",
    desc: "Browse 1,000+ MCP servers. Search by name, tags, or capability. One-click install commands for Claude Desktop.",
    color: "#f59e0b",
    photo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=400&fit=crop&q=80",
  },
  {
    title: "Live Playground",
    desc: "Simulate JSON-RPC calls against your server. See formatted request/response logs before you deploy.",
    color: "#a78bfa",
    photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop&q=80",
  },
  {
    title: "Config Generator",
    desc: "Auto-generates claude_desktop_config.json, package.json, and production-ready TypeScript following the official SDK.",
    color: "#3b82f6",
    photo: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&h=400&fit=crop&q=80",
  },
];

const STATS = [
  { value: "3", label: "MCP Primitives", sub: "Tools · Resources · Prompts" },
  { value: "2025-11-25", label: "Spec Version", sub: "Latest MCP specification" },
  { value: "0", label: "Boilerplate", sub: "Lines you write manually" },
];

export default function LandingPage() {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <div className="min-h-screen bg-[#070b14]">
      {/* Nav */}
      <nav className="border-b border-white/[0.04] px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-forge-500 to-forge-700 flex items-center justify-center text-sm font-bold">
              ⚡
            </div>
            <span className="font-mono font-bold text-[15px]">MCP Forge</span>
            <span className="text-[10px] text-slate-600 font-mono">v1.0.0</span>
          </div>
          <div className="flex items-center gap-6">
            <a
              href="https://github.com/YOUR_USERNAME/mcp-forge"
              className="text-xs text-slate-500 hover:text-slate-300 font-mono transition-colors"
              target="_blank"
              rel="noopener noreferrer"
            >
              GitHub
            </a>
            <a
              href="https://modelcontextprotocol.io"
              className="text-xs text-slate-500 hover:text-slate-300 font-mono transition-colors"
              target="_blank"
              rel="noopener noreferrer"
            >
              MCP Docs
            </a>
            <Link
              href="/builder"
              className="px-4 py-2 bg-forge-500/10 border border-forge-500/30 rounded-lg text-forge-400 text-xs font-mono font-semibold hover:bg-forge-500/20 transition-all"
            >
              Open Builder →
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="px-6 pt-20 pb-16">
        <div className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
          <div
            className={`transition-all duration-1000 ${
              mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
            }`}
          >
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-forge-500/8 border border-forge-500/20 rounded-full mb-6">
              <span className="w-2 h-2 rounded-full bg-forge-500 animate-pulse" />
              <span className="text-[10px] font-mono text-forge-400 font-semibold tracking-wider uppercase">
                MCP Spec 2025-11-25
              </span>
            </div>

            <h1 className="text-4xl lg:text-5xl font-bold leading-tight mb-6 tracking-tight">
              Build MCP Servers
              <br />
              <span className="text-forge-400">Visually.</span>
            </h1>

            <p className="text-lg text-slate-400 leading-relaxed mb-8 max-w-lg">
              Stop writing boilerplate. Design tools, resources, and prompts
              through a visual interface — get production-ready TypeScript code
              that follows the official SDK patterns.
            </p>

            <div className="flex gap-4">
              <Link
                href="/builder"
                className="px-6 py-3 bg-forge-500 hover:bg-forge-600 text-white font-mono font-semibold text-sm rounded-lg transition-all glow-green"
              >
                Start Building →
              </Link>
              <a
                href="https://github.com/YOUR_USERNAME/mcp-forge"
                className="px-6 py-3 bg-white/[0.03] border border-white/[0.08] hover:border-white/[0.15] text-slate-300 font-mono text-sm rounded-lg transition-all"
                target="_blank"
                rel="noopener noreferrer"
              >
                View Source
              </a>
            </div>
          </div>

          <div
            className={`transition-all duration-1000 delay-300 ${
              mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
            }`}
          >
            <AnimatedCode />
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="px-6 py-12 border-y border-white/[0.04]">
        <div className="max-w-4xl mx-auto grid grid-cols-3 gap-8">
          {STATS.map((stat) => (
            <div key={stat.label} className="text-center">
              <div className="text-2xl font-mono font-bold text-forge-400 mb-1">
                {stat.value}
              </div>
              <div className="text-xs font-mono text-slate-400 font-semibold">
                {stat.label}
              </div>
              <div className="text-[10px] font-mono text-slate-600 mt-1">
                {stat.sub}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="px-6 py-20">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-2xl font-bold mb-3">
              Everything you need to ship MCP servers
            </h2>
            <p className="text-sm text-slate-500 font-mono max-w-lg mx-auto">
              From visual design to production deployment — one tool for the
              entire MCP server lifecycle.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="rounded-xl border border-white/[0.04] hover:border-white/[0.12] transition-all group overflow-hidden relative"
              >
                {/* Photo background */}
                <div className="absolute inset-0">
                  <img
                    src={f.photo}
                    alt=""
                    className="w-full h-full object-cover"
                    loading="lazy"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-[#070b14] via-[#070b14]/90 to-[#070b14]/60" />
                </div>
                {/* Content */}
                <div className="relative p-6 pt-24">
                  <h3
                    className="font-semibold text-[15px] mb-2 transition-colors"
                    style={{ color: f.color }}
                  >
                    {f.title}
                  </h3>
                  <p className="text-sm text-slate-400 leading-relaxed font-mono">
                    {f.desc}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* MCP Explanation */}
      <section className="px-6 py-16 border-t border-white/[0.04]">
        <div className="max-w-3xl mx-auto text-center">
          <div className="text-xs font-mono text-slate-600 mb-4 tracking-widest uppercase">
            What is MCP?
          </div>
          <p className="text-lg text-slate-300 leading-relaxed mb-6">
            The Model Context Protocol is an open standard by Anthropic — now
            under the Linux Foundation — that lets AI applications connect to
            external tools and data through a unified interface. Adopted by
            OpenAI, Google DeepMind, Microsoft, and thousands of developers.
          </p>
          <div className="flex justify-center gap-6 text-[10px] font-mono text-slate-600">
            <span>JSON-RPC 2.0</span>
            <span>·</span>
            <span>stdio / HTTP / SSE</span>
            <span>·</span>
            <span>Tools · Resources · Prompts</span>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-6 py-20 border-t border-white/[0.04]">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to build?</h2>
          <p className="text-slate-500 font-mono text-sm mb-8">
            Open the builder and create your first MCP server in minutes.
          </p>
          <Link
            href="/builder"
            className="inline-block px-8 py-4 bg-forge-500 hover:bg-forge-600 text-white font-mono font-bold text-sm rounded-lg transition-all glow-green"
          >
            ⚡ Launch MCP Forge
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="px-6 py-8 border-t border-white/[0.04]">
        <div className="max-w-6xl mx-auto flex items-center justify-between text-[10px] font-mono text-slate-700">
          <div className="flex items-center gap-2">
            <span className="text-forge-500">⚡</span>
            <span>MCP Forge v1.0.0</span>
          </div>
          <div className="flex gap-6">
            <span>MCP Spec 2025-11-25</span>
            <span>Built with Next.js + TypeScript</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
