import React from 'react';
import { render, screen, act } from '@testing-library/react';
import Hero from '@/components/landing/Hero';

jest.mock('next/link', () => {
  const MockLink = ({ children, href, ...rest }: any) => (
    <a href={href} {...rest}>{children}</a>
  );
  MockLink.displayName = 'MockLink';
  return MockLink;
});

describe('Hero component', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });
  afterEach(() => {
    jest.useRealTimers();
  });
  test('renders the main heading', () => {
    render(<Hero />);
    expect(screen.getByText('Build MCP Servers')).toBeInTheDocument();
    expect(screen.getByText('Visually.')).toBeInTheDocument();
  });
  test('renders MCP spec badge', () => {
    render(<Hero />);
    expect(screen.getByText('MCP Spec 2025-11-25')).toBeInTheDocument();
  });
  test('renders Start Building link pointing to /builder', () => {
    render(<Hero />);
    const link = screen.getByText('Start Building →');
    expect(link).toBeInTheDocument();
    expect(link.closest('a')).toHaveAttribute('href', '/builder');
  });
  test('renders View Source link pointing to GitHub', () => {
    render(<Hero />);
    const link = screen.getByText('View Source');
    expect(link.closest('a')).toHaveAttribute(
      'href',
      'https://github.com/mpalmer79/mcp-forge'
    );
  });
  test('animates code lines over time', () => {
    const { container } = render(<Hero />);
    act(() => {
      jest.advanceTimersByTime(120 * 5);
    });
    const codeBlock = container.querySelector('.code-block');
    expect(codeBlock).toBeTruthy();
  });
  test('shows the code block file label', () => {
    render(<Hero />);
    expect(screen.getByText(/index\.ts — generated by MCP Forge/)).toBeInTheDocument();
  });
  test('renders description paragraph', () => {
    render(<Hero />);
    expect(screen.getByText(/Stop writing boilerplate/)).toBeInTheDocument();
  });
});
